import { Incident, ResponderUnit, AidPoint } from '@/types/incident';

export const mockIncidents: Incident[] = [
  {
    id: 'INC-001',
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60000).toISOString(),
    source: 'voice',
    transcript: 'Help! Building collapsed, many people trapped inside!',
    language: 'en',
    lat: 12.9716,
    lon: 77.5946,
    address: 'MG Road, Bangalore',
    type: 'earthquake',
    severity_score: 95,
    severity_level: 'critical',
    status: 'dispatched',
    reporter_contact: '+91XXXXXX1234',
    anonymous: false,
    victims_count: 15,
    description: 'Building collapse with multiple casualties',
    eta_minutes: 8,
  },
  {
    id: 'INC-002',
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60000).toISOString(),
    source: 'app',
    language: 'hi',
    lat: 12.9606,
    lon: 77.6389,
    address: 'Koramangala, Bangalore',
    type: 'fire',
    severity_score: 78,
    severity_level: 'high',
    status: 'enroute',
    anonymous: true,
    victims_count: 3,
    description: 'Fire in residential complex, 3rd floor',
    eta_minutes: 5,
  },
  {
    id: 'INC-003',
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
    source: 'voice',
    transcript: 'आग लग गई है, कृपया जल्दी आइए!',
    language: 'hi',
    lat: 12.9352,
    lon: 77.6245,
    address: 'BTM Layout, Bangalore',
    type: 'flood',
    severity_score: 60,
    severity_level: 'medium',
    status: 'rescued',
    reporter_contact: '+91XXXXXX5678',
    anonymous: false,
    victims_count: 8,
    description: 'Flash flood, families stranded on rooftop',
    eta_minutes: 0,
  },
  {
    id: 'INC-004',
    created_at: new Date(Date.now() - 2 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60000).toISOString(),
    source: 'app',
    language: 'en',
    lat: 12.9165,
    lon: 77.6101,
    address: 'Jayanagar, Bangalore',
    type: 'medical',
    severity_score: 85,
    severity_level: 'high',
    status: 'new',
    anonymous: false,
    victims_count: 1,
    description: 'Heart attack, immediate medical assistance needed',
    eta_minutes: undefined,
  },
];

export const mockResponderUnits: ResponderUnit[] = [
  {
    id: 'UNIT-001',
    org: 'fire',
    name: 'Fire Station Alpha',
    phone: '+91XXXXXX0001',
    capabilities: ['fire', 'rescue', 'hazmat'],
    base_lat: 12.9700,
    base_lon: 77.5900,
    availability_status: 'available',
    current_lat: 12.9710,
    current_lon: 77.5920,
  },
  {
    id: 'UNIT-002',
    org: 'ambulance',
    name: 'Emergency Medical Team 1',
    phone: '+91XXXXXX0002',
    capabilities: ['trauma', 'cardiac', 'basic'],
    base_lat: 12.9600,
    base_lon: 77.6300,
    availability_status: 'busy',
    current_lat: 12.9606,
    current_lon: 77.6389,
  },
  {
    id: 'UNIT-003',
    org: 'police',
    name: 'Police Patrol Delta',
    phone: '+91XXXXXX0003',
    capabilities: ['crowd_control', 'traffic', 'security'],
    base_lat: 12.9500,
    base_lon: 77.6200,
    availability_status: 'available',
  },
  {
    id: 'UNIT-004',
    org: 'volunteer',
    name: 'Community Response Team',
    phone: '+91XXXXXX0004',
    capabilities: ['first_aid', 'search', 'supplies'],
    base_lat: 12.9400,
    base_lon: 77.6100,
    availability_status: 'available',
  },
];

export const mockAidPoints: AidPoint[] = [
  {
    id: 'AID-001',
    type: 'hospital',
    name: 'City General Hospital',
    lat: 12.9650,
    lon: 77.5950,
    hours: '24/7',
    capacity: 500,
    current_occupancy: 320,
    distance: 2.3,
    contact: '1800-XXX-XXXX',
  },
  {
    id: 'AID-002',
    type: 'shelter',
    name: 'Community Relief Center',
    lat: 12.9550,
    lon: 77.6050,
    hours: '6:00 AM - 10:00 PM',
    capacity: 200,
    current_occupancy: 45,
    distance: 1.8,
  },
  {
    id: 'AID-003',
    type: 'police',
    name: 'MG Road Police Station',
    lat: 12.9720,
    lon: 77.5960,
    hours: '24/7',
    distance: 0.5,
    contact: '100',
  },
  {
    id: 'AID-004',
    type: 'pharmacy',
    name: '24x7 Emergency Pharmacy',
    lat: 12.9680,
    lon: 77.5980,
    hours: '24/7',
    distance: 1.2,
  },
  {
    id: 'AID-005',
    type: 'water',
    name: 'Emergency Water Distribution Point',
    lat: 12.9580,
    lon: 77.6020,
    hours: '8:00 AM - 8:00 PM',
    distance: 3.5,
  },
];

export const disasterGuidance = {
  fire: {
    title: 'Fire Emergency',
    steps: [
      'Stay low to avoid smoke inhalation',
      'Feel doors before opening - if hot, find another exit',
      'Cover nose and mouth with wet cloth if possible',
      'Never use elevators during fire',
      'Call 101 immediately',
      'Move to assembly point after evacuation',
    ],
  },
  flood: {
    title: 'Flood Emergency',
    steps: [
      'Move to higher ground immediately',
      'Avoid walking in moving water',
      'Stay away from electrical equipment',
      'Do not drive through flooded areas',
      'Boil water before drinking',
      'Signal for help from rooftop if trapped',
    ],
  },
  earthquake: {
    title: 'Earthquake Emergency',
    steps: [
      'Drop, Cover, and Hold On',
      'Stay away from windows and heavy objects',
      'If outdoors, move to open area',
      'Do not use elevators',
      'Check for injuries after shaking stops',
      'Be prepared for aftershocks',
    ],
  },
  medical: {
    title: 'Medical Emergency',
    steps: [
      'Check breathing and pulse',
      'Do not move injured unless in immediate danger',
      'Apply pressure to stop bleeding',
      'Keep the person warm and comfortable',
      'Provide CPR if trained and needed',
      'Stay with patient until help arrives',
    ],
  },
};